### ISSUE TITLE
analytics

### ISSUE THREAD

**Issue by brianblain** [jazzto/2015#32]
I was checking analytics to see the bump in traffic after media launch.  It peaked 1900 sessions.  Looks like last year it was 2900.  Hmmm.

I want to give Pat a traffic report for the week of the launch (lets say till next monday)

Interesting that it indicates more visitors with Apple mobile than Apple computers

**Comment by andrewfn** [comment]
Don't forget that we didn't have the mobile app last year, which you have to take into account.
- This is because the mobile device stores the session from one day to the next, so will not record it as a new session. You should look at page hits, not sessions or you **will** get a lower number.
  I'll take a look at the numbers if you like.

**Comment by andrewfn** [comment]
I've spend the last hour researching the statistics:
- Once you have a mobile site it is like comparing apples with oranges since it looks to Google as if people with the app are connected all the time and just have one session
- Because of the misconfiguration that I have just fixed, many mobile users would not have been counted by Google. Fortunately Drupal itself has a statistics log and I can tell you that exactly 933 extra people viewed the site but were not counted by Google. This alone would explain the difference from last year.

I think that once you take both factors into consideration, we were probably around 10-20% up from last year.

**Comment by brianblain** [comment]
can you calculate the stats for the week following the media launch (Apr 14-21)  Thanks

**Comment by andrewfn** [comment]
ok, will do. On first sight it looks very similar to last year.

**Comment by andrewfn** [comment]
I have crunched the numbers.
- For Apr 14-21:
- 2014: 63434
- 2015: 65151
- Increase: 3% from last year.

The increase is likely more than that because not all the mobile activity gets into the analytics.
Also it died away much more quickly last year after the launch.
This week we are up 20% over last year!

**Comment by andrewfn** [comment]
I'm going to do you another report for the following week because you'll see that the results are up 20-30% on last year!

**Comment by andrewfn** [comment]
Here is the second week (April 21-27)
- 2014: 21617
- 2015: 26946

**Up by 25% over last year!!**
The numbers from the launch day are probably related to the listener figures for jazzFM.
But the numbers now are actually more important because they represent an increasing groundswell of interest.
@joshgrossman
