### ISSUE TITLE
Name change for contributor

### ISSUE THREAD

**Issue by joshgrossman** [jazzto/2015#35]
Hi Andrew - see the note from a contributor below:
Is that doable?

**Comment by andrewfn** [comment]
That should be doable

**Comment by andrewfn** [comment]
I think I have changed all the references, but let me know if I have missed anything.
Once you are happy with the changes, please close the issue, then I know it's done.

**Comment by joshgrossman** [comment]
Thanks Andrew.  Just one more spot, I think:

**Comment by andrewfn** [comment]
Unfortunately changing the archive is a different matter.
Altering content is fairly easy.
Changing the URL would be a lot of work. That is because it will break all inbound links to that page within the archive (not a problem in the live site because Drupal makes all the changes automatically)
There are around 200 pages that link to the url, and I would have to manually find and edit them all which could take a few hours.
What I have done is to create a copy of the original page, but I can't delete the original page without breaking all the inbound links. Does that make sense?

**Comment by joshgrossman** [comment]
Gotcha.  Sorry for confusion:  it's actually just the name in the content of the page I was suggested be updated (second bullet point)...

**Comment by andrewfn** [comment]
Ok, that was no problem to do.
