### ISSUE TITLE
concerts prior to june 18

### ISSUE THREAD

**Issue by joshgrossman** [jazzto/2015#36]
I've added a concert on June 16 but I can't seem to find it by doing a search.  Is the site currently set up to display concerts only in the June 18-29 date range?  Here's the concert I just created:

http://torontojazz.com/concert/tara-davidson-trio-0

**Comment by andrewfn** [comment]
The search data gets updated every 30 mins. I just searched for Tara Davidson Trio and it found me the concert, so it looks good.
In many cases (but not actually this one) you can force changes to happen immediately by manually clearing the cache. Because this comes up so frequently, I have created an issue "how to clear the cache" which we will leave open as a quick reference.
Does the search work for you now?

**Comment by joshgrossman** [comment]
And there it is - thanks.  I was sure I had cleared the cache...

Josh
